### PR TITLE
Update version 18.3

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Update version 18.3

### CODE REVIEW

**Comment by lemenkov** [comment]
Hello @Gsantomaggio !
Just a heads-up - I'm talking with @systemd upstream about moving this tiny library under @systemd umbrella.

http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/36684

**Comment by Gsantomaggio** [comment]
Hi @lemenkov 
That's great! The Centos/Debian packaging is not ready yet. 
Let me know if needed .
Thank you.

**Comment by michaelklishin** [comment]
@lemenkov that would be pretty sweet!

**Comment by lemenkov** [comment]
@Gsantomaggio @michaelklishin done!

https://github.com/systemd/erlang-sd_notify

**Comment by lemenkov** [comment]
@Gsantomaggio feel free to commit to that repository

**Comment by Gsantomaggio** [comment]
Thank you @lemenkov

**Pull request merged**
